@startuml

class main {
    + main() : void
}


class feuPieton{
+ etat : String
+ ChangeCouleur() : void
+ ChangeEtat() : void
+ getEtat() : String
+ getCouleur() : String
}

interface strategy{
+ ChangeCouleur() : void
}

class startegyGermany implements strategy{
+ ChangeCouleur(color : Couleur) : void
}


class startegyFrance implements strategy{
+ ChangeCouleur(color : Couleur) : void
}

enum Couleur{
    Vert
    Rouge
    Orange
}


feuPieton *-- strategy
feuPieton *-- Couleur
main --> feuPieton


@enduml
