@startuml

class feuPieton{
+ etat : String
+ Couleur : String
+ ChangeCouleur() : void
+ ChangeEtat() : void
+ getEtat() : String
+ getCouleur() : String


}

interface strategy{
+ ChangeCouleur() : void
}

class startegyGermany implements strategy{
+ ChangeCouleur() : void
}

class startegyFrance implements strategy{
+ ChangeCouleur() : void
}

feuPieton *-- strategy

@enduml
