@startuml

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods
hide interface attributes

class AuBrasseur {
	+ {static} main(args : String[])
}

@enduml